<a href="https://colab.research.google.com/github/Vagoberto10/AluraStore/blob/main/AluraStoreLatam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importación de datos

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [19]:
tienda.isna().sum()
ingresosTienda1 = tienda['Precio'].sum()
ingresosTienda1
formatodinero = "${:,.2f}".format(ingresosTienda1)
formatodinero

'$1,150,880,400.00'

In [25]:
ingresosTienda2 = tienda2['Precio'].sum()
ingresosTienda2
formatodinero2 = "${:,.2f}".format(ingresosTienda2)
formatodinero2

'$1,116,343,500.00'

In [26]:
ingresosTienda3 = tienda3['Precio'].sum()
ingresosTienda3
formatodinero3 = "${:,.2f}".format(ingresosTienda3)
formatodinero3

'$1,098,019,600.00'

In [27]:
ingresosTienda4 = tienda4['Precio'].sum()
ingresosTienda4
formatodinero4 = "${:,.2f}".format(ingresosTienda4)
formatodinero4

'$1,038,375,700.00'

# 2. Ventas por categoría

In [97]:
vendidos1 = tienda['Categoría del Producto']
vendidos1.value_counts()

Categoría del Producto
Muebles                    465
Electrónicos               448
Juguetes                   324
Electrodomésticos          312
Deportes y diversión       284
Instrumentos musicales     182
Libros                     173
Artículos para el hogar    171
Name: count, dtype: int64

In [101]:
#Especifico de cantidad de productos por categoria
productosvendidos1 = tienda.groupby('Categoría del Producto')['Producto'].value_counts()
productosvendidos1

Categoría del Producto   Producto
Artículos para el hogar  Cubertería                     52
                         Set de ollas                   43
                         Set de vasos                   41
                         Olla de presión                35
Deportes y diversión     Balón de baloncesto            55
                         Bicicleta                      54
                         Vaso térmico                   54
                         Balón de voleibol              42
                         Cuerda para saltar             40
                         Mochila                        39
Electrodomésticos        Microondas                     60
                         Secadora de ropa               58
                         Refrigerador                   54
                         Lavavajillas                   48
                         Lavadora de ropa               47
                         Estufa                         45
Electrónicos             TV LED UHD 4K                  60
                         Impresora                      54
                         Auriculares                    50
                         Iphone 15                      49
                         Smart TV                       44
                         Smartwatch                     43
                         Tablet ABXY                    42
                         Asistente virtual              40
                         Auriculares con micrófono      33
                         Celular ABXY                   33
Instrumentos musicales   Batería                        53
                         Guitarra eléctrica             47
                         Guitarra acústica              46
                         Pandereta                      36
Juguetes                 Bloques de construcción        56
                         Carrito de control remoto      52
                         Ajedrez de madera              49
                         Cubo mágico 8x8                44
                         Juego de mesa                  43
                         Dinosaurio Rex                 40
                         Muñeca bebé                    40
Libros                   Modelado predictivo            51
                         Dashboards con Power BI        42
                         Iniciando en programación      41
                         Ciencia de datos con Python    39
Muebles                  Armario                        60
                         Mesa de noche                  56
                         Silla de oficina               46
                         Sofá reclinable                46
                         Cama box                       44
                         Cama king                      44
                         Kit de bancas                  44
                         Mesa de centro                 44
                         Sillón                         41
                         Mesa de comedor                40
Name: count, dtype: int64

In [98]:
vendidos2 = tienda2['Categoría del Producto']
vendidos2.value_counts()

Categoría del Producto
Muebles                    442
Electrónicos               422
Juguetes                   313
Electrodomésticos          305
Deportes y diversión       275
Instrumentos musicales     224
Libros                     197
Artículos para el hogar    181
Name: count, dtype: int64

In [102]:
#Especifico de cantidad de productos por categoria
productosvendidos2 = tienda2.groupby('Categoría del Producto')['Producto'].value_counts()
productosvendidos2

Categoría del Producto   Producto
Artículos para el hogar  Set de ollas                   52
                         Set de vasos                   46
                         Olla de presión                44
                         Cubertería                     39
Deportes y diversión     Cuerda para saltar             50
                         Vaso térmico                   47
                         Balón de voleibol              46
                         Bicicleta                      45
                         Mochila                        45
                         Balón de baloncesto            42
Electrodomésticos        Microondas                     62
                         Secadora de ropa               57
                         Lavadora de ropa               49
                         Refrigerador                   49
                         Lavavajillas                   46
                         Estufa                         42
Electrónicos             Iphone 15                      55
                         TV LED UHD 4K                  45
                         Auriculares con micrófono      44
                         Smartwatch                     44
                         Tablet ABXY                    44
                         Celular ABXY                   41
                         Smart TV                       40
                         Asistente virtual              38
                         Auriculares                    37
                         Impresora                      34
Instrumentos musicales   Batería                        61
                         Guitarra acústica              58
                         Pandereta                      58
                         Guitarra eléctrica             47
Juguetes                 Bloques de construcción        54
                         Muñeca bebé                    48
                         Carrito de control remoto      47
                         Ajedrez de madera              45
                         Cubo mágico 8x8                45
                         Dinosaurio Rex                 42
                         Juego de mesa                  32
Libros                   Iniciando en programación      65
                         Modelado predictivo            46
                         Ciencia de datos con Python    43
                         Dashboards con Power BI        43
Muebles                  Armario                        54
                         Silla de oficina               49
                         Cama box                       47
                         Cama king                      45
                         Kit de bancas                  45
                         Mesa de centro                 45
                         Mesa de noche                  44
                         Sofá reclinable                44
                         Sillón                         35
                         Mesa de comedor                34
Name: count, dtype: int64

In [103]:
vendidos3 = tienda3['Categoría del Producto']
vendidos3.value_counts()

Categoría del Producto
Muebles                    499
Electrónicos               451
Juguetes                   315
Electrodomésticos          278
Deportes y diversión       277
Libros                     185
Instrumentos musicales     177
Artículos para el hogar    177
Name: count, dtype: int64

In [104]:
#Especifico de cantidad de productos por categoria
productosvendidos3 = tienda3.groupby('Categoría del Producto')['Producto'].value_counts()
productosvendidos3

Categoría del Producto   Producto
Artículos para el hogar  Set de ollas                   55
                         Olla de presión                47
                         Cubertería                     39
                         Set de vasos                   36
Deportes y diversión     Cuerda para saltar             53
                         Bicicleta                      52
                         Balón de baloncesto            50
                         Balón de voleibol              48
                         Vaso térmico                   38
                         Mochila                        36
Electrodomésticos        Estufa                         53
                         Lavavajillas                   52
                         Refrigerador                   50
                         Secadora de ropa               45
                         Lavadora de ropa               42
                         Microondas                     36
Electrónicos             Smart TV                       54
                         Impresora                      50
                         Tablet ABXY                    48
                         Iphone 15                      46
                         Smartwatch                     46
                         Celular ABXY                   44
                         Auriculares                    43
                         TV LED UHD 4K                  42
                         Asistente virtual              39
                         Auriculares con micrófono      39
Instrumentos musicales   Pandereta                      51
                         Guitarra acústica              47
                         Batería                        41
                         Guitarra eléctrica             38
Juguetes                 Carrito de control remoto      52
                         Juego de mesa                  52
                         Ajedrez de madera              47
                         Dinosaurio Rex                 46
                         Cubo mágico 8x8                44
                         Muñeca bebé                    39
                         Bloques de construcción        35
Libros                   Modelado predictivo            53
                         Ciencia de datos con Python    46
                         Iniciando en programación      46
                         Dashboards con Power BI        40
Muebles                  Kit de bancas                  57
                         Cama king                      56
                         Mesa de comedor                56
                         Mesa de noche                  55
                         Armario                        49
                         Sillón                         47
                         Cama box                       46
                         Silla de oficina               46
                         Sofá reclinable                45
                         Mesa de centro                 42
Name: count, dtype: int64

In [105]:
vendidos4 = tienda4['Categoría del Producto']
vendidos4.value_counts()

Categoría del Producto
Muebles                    480
Electrónicos               451
Juguetes                   338
Deportes y diversión       277
Electrodomésticos          254
Artículos para el hogar    201
Libros                     187
Instrumentos musicales     170
Name: count, dtype: int64

In [106]:
#Especifico de cantidad de productos por categoria
productosvendidos4 = tienda4.groupby('Categoría del Producto')['Producto'].value_counts()
productosvendidos4

Categoría del Producto   Producto
Artículos para el hogar  Cubertería                     59
                         Set de ollas                   50
                         Olla de presión                46
                         Set de vasos                   46
Deportes y diversión     Balón de baloncesto            50
                         Balón de voleibol              48
                         Vaso térmico                   48
                         Bicicleta                      45
                         Cuerda para saltar             43
                         Mochila                        43
Electrodomésticos        Microondas                     48
                         Estufa                         47
                         Lavavajillas                   43
                         Secadora de ropa               40
                         Lavadora de ropa               38
                         Refrigerador                   38
Electrónicos             Smart TV                       54
                         Asistente virtual              50
                         Impresora                      50
                         Iphone 15                      48
                         Tablet ABXY                    45
                         Auriculares                    44
                         Auriculares con micrófono      42
                         TV LED UHD 4K                  40
                         Celular ABXY                   39
                         Smartwatch                     39
Instrumentos musicales   Pandereta                      52
                         Batería                        48
                         Guitarra acústica              37
                         Guitarra eléctrica             33
Juguetes                 Carrito de control remoto      55
                         Bloques de construcción        54
                         Juego de mesa                  48
                         Muñeca bebé                    48
                         Cubo mágico 8x8                47
                         Dinosaurio Rex                 47
                         Ajedrez de madera              39
Libros                   Dashboards con Power BI        56
                         Modelado predictivo            50
                         Iniciando en programación      43
                         Ciencia de datos con Python    38
Muebles                  Cama box                       62
                         Cama king                      56
                         Mesa de comedor                55
                         Mesa de noche                  55
                         Sofá reclinable                47
                         Sillón                         45
                         Mesa de centro                 44
                         Kit de bancas                  42
                         Silla de oficina               40
                         Armario                        34
Name: count, dtype: int64

# 3. Calificación promedio de la tienda

In [112]:
tienda.head()
calificacion = tienda['Calificación'].mean().round(2)
calificacion

np.float64(3.98)

In [113]:
tienda2.head()
calificacion2 = tienda2['Calificación'].mean().round(2)
calificacion2

np.float64(4.04)

In [114]:
tienda3.head()
calificacion3 = tienda3['Calificación'].mean().round(2)
calificacion3

np.float64(4.05)

In [115]:
tienda4.head()
calificacion4 = tienda4['Calificación'].mean().round(2)
calificacion4

np.float64(4.0)

# 4. Productos más y menos vendidos

# 5. Envío promedio por tienda